
BPTT = 70
DROPOUT = 0.4
DROPOUT_HID = 0.3
DROPOUT_INP = 0.4
DROPOUT_EMB = 0.1
WEIGHT_DROP = 0.5

ALPHA = 2
BETA = 1
WEIGHT_DECAY = 1.2e-6
OPTIMIZER = 'sgd'
NONMONO = 5


MODEL_TYPE = "LSTM"
#DATA_PATH = "/projects/tir1/users/kchandu/language_model_data/sample_data/penn/"
DATA_PATH = "./data/penn"
#MODEL_SAVE_PATH = "/projects/tir1/users/kchandu/language_models/model.pt"
MODEL_SAVE_PATH = "./Penn-Fine.pt"

WORD_FACTOR = "WORD_FACTOR"
#LANGUAGE_FACTOR = "LANG_FACTOR"
#SOUNDEX_FACTOR = "SOUNDEX_FACTOR"
#FACTORS_LIST = [WORD_FACTOR, LANGUAGE_FACTOR, SOUNDEX_FACTOR]

WORD_EMBEDDING_SIZE    = 400
#LANG_EMBEDDING_SIZE    = 2
#SOUNDEX_EMBEDDING_SIZE = 64

NUMBER_HIDDEN = 1150

NUMBER_LAYERS = 3

INITIAL_LEARNING_RATE = 30
CLIP_GRADIENTS = 0.25
EPOCH_MAX = 300

BATCH_SIZE = 20
EVAL_BATCH_SIZE = 10

MAX_SEQ_LEN = 35

#DROPOUT_PERCENT = 0.2

RNG_SEED = 28

USE_CUDA = False

DEUBG_LOG_INTERVAL = 1

TIED = True

WEIGHT_INIT = 0.1


