MODEL_TYPE = "LSTM"
DATA_PATH = "output/output.txt"
MODEL_SAVE_PATH = "output/model.pt"

WORD_FACTOR = "WORD_FACTOR"
LANGUAGE_FACTOR = "LANG_FACTOR"
SOUNDEX_FACTOR = "SOUNDEX_FACTOR"
FACTORS_LIST = [WORD_FACTOR, LANGUAGE_FACTOR, SOUNDEX_FACTOR]

WORD_EMBEDDING_SIZE    = 128
LANG_EMBEDDING_SIZE    = 2
SOUNDEX_EMBEDDING_SIZE = 64

NUMBER_HIDDEN = 128

NUMBER_LAYERS = 1

INITIAL_LEARNING_RATE = 0.01
CLIP_GRADIENTS = 0.25
EPOCH_MAX = 40

BATCH_SIZE = 100
EVAL_BATCH_SIZE = 10

MAX_SEQ_LEN = 35

DROPOUT_PERCENT = 0.2

RNG_SEED = 111

USE_CUDA = False

DEUBG_LOG_INTERVAL = 1

TIE_WEIGHTS = True